/// Plain Dart model for the currently signed-in user.
/// Previously generated by Drift; now a hand-written class so the
/// SQLite `users` table can be removed while keeping the rest of the
/// auth flow intact.
class UserEntity {
  const UserEntity({
    required this.id,
    required this.nisn,
    required this.passwordHash,
    required this.role,
    required this.fullname,
    this.email,
    this.phone,
    this.avatarUrl,
    required this.isActive,
    required this.createdAt,
    required this.updatedAt,
    this.syncedAt,
  });

  final String id;
  final String nisn;
  final String passwordHash;
  final String role;
  final String fullname;
  final String? email;
  final String? phone;
  final String? avatarUrl;
  final bool isActive;
  final int createdAt;
  final int updatedAt;
  final int? syncedAt;

  UserEntity copyWith({String? avatarUrl}) => UserEntity(
        id: id,
        nisn: nisn,
        passwordHash: passwordHash,
        role: role,
        fullname: fullname,
        email: email,
        phone: phone,
        avatarUrl: avatarUrl ?? this.avatarUrl,
        isActive: isActive,
        createdAt: createdAt,
        updatedAt: updatedAt,
        syncedAt: syncedAt,
      );
}
